### ISSUE TITLE
Remove 'crazy' from the characteristics pull down menu

### ISSUE THREAD

**Issue by markvoortman** [markvoortman/actordatabase#2]

**Comment by tcampbPPU** [comment]
Added these just to fill the selection: Energetic, Imaginative, Intelligence, Charisma.

**Comment by markvoortman** [comment]
Nice! I'm not sure what options should actually be available. Marty is working on a list of desired changes so if it's on that list I will post it here.

**Comment by tcampbPPU** [comment]
Sounds good!

And I will continue to work on the drop down for the hair color.

**Comment by markvoortman** [comment]
Closed by 7570ec966314e891ce5a2973f19a53ddc75eca07.
