### ISSUE TITLE
Verify buckets are working correctly

### ISSUE THREAD

**Issue by markvoortman** [markvoortman/actordatabase#50]
This is what they said:

> Bins/folders or “buckets’ - Trevor said that was a function that doesn’t work.  You should be able to create new folders/‘buckets’ for each shooting date or other sorting categories and ‘move’ selected people into them by flagging/field. This info of what bucket someone is in should then show on their main info page, so you can quickly see if someone was used & when.

Should they be able to do this?

**Comment by tcampbPPU** [comment]
Just checked it out on mine, Adding the actors to a bucket functionality worked for me If that bucket was already created in the past). But for some reason the option to create a new bucket to add the actors in was not there.

**Comment by tcampbPPU** [comment]
Which is strange that it is no longer there it had been on option previously.

**Comment by lkonat** [comment]
Oh, okayyy. We did not have that functionality. The bucket feature was only meant to allow admins to come back to their saved searches. Users were only allowed to see the content of a bucket or add new actor to an existing bucket by right click on the actor profile after a search.

**Comment by lkonat** [comment]
On this version, users are  only allowed to create bucket after a search. There was no feature to allow them to randomly create a new bucket

**Comment by lkonat** [comment]
So,  each search gives user an option to save a search  as a bucket or not.

**Comment by markvoortmanppu** [comment]
Addressed by #51.
